/* line 1, src/Main/components/Navigation/Navigation.module.scss */
.navigation {
  background-color: var(--bg-grey-medium);
  display: flex;
  position: fixed;
  width: 100vw;
  height: 5rem;
  justify-content: space-between;
  color: white; }
  /* line 10, src/Main/components/Navigation/Navigation.module.scss */
  .navigation > * {
    display: flex;
    align-items: center;
    justify-content: center;
    cursor: pointer; }
  /* line 17, src/Main/components/Navigation/Navigation.module.scss */
  .navigation__dropdown {
    display: flex;
    align-items: stretch; }
    /* line 21, src/Main/components/Navigation/Navigation.module.scss */
    .navigation__dropdown > * {
      width: 100%;
      text-align: center; }
  /* line 27, src/Main/components/Navigation/Navigation.module.scss */
  .navigation__logo {
    font-size: 1.5rem; }
  /* line 31, src/Main/components/Navigation/Navigation.module.scss */
  .navigation__desktop {
    flex-basis: 60vw; }
  /* line 35, src/Main/components/Navigation/Navigation.module.scss */
  .navigation__nav_items {
    display: flex;
    width: 100%;
    height: 100%;
    transition: all .2s; }
    /* line 41, src/Main/components/Navigation/Navigation.module.scss */
    .navigation__nav_items > * {
      height: 100%;
      width: 100%;
      display: flex;
      align-items: center;
      justify-content: space-around; }
      /* line 48, src/Main/components/Navigation/Navigation.module.scss */
      .navigation__nav_items > *:hover {
        transform: scale(0.9) translateY(5px);
        border-bottom: 5px solid grey; }
