/* line 5, src/Main/components/Landing/ProductivitySection/ProductivitySection.module.scss */
.productivity__back_ground {
  position: relative;
  margin-top: 10vh;
  background-size: cover;
  background-position: center;
  clip-path: polygon(0 10%, 100% 0, 100% 90%, 0 100%);
  background-image: linear-gradient(to bottom, rgba(126, 213, 111, 0.8), rgba(40, 180, 133, 0.8)); }

/* line 17, src/Main/components/Landing/ProductivitySection/ProductivitySection.module.scss */
.productivity__img {
  height: 80vh;
  width: 100%;
  object-fit: fill; }
