/* line 10, src/index.scss */
* {
  margin: 0;
  padding: 0; }

/* line 15, src/index.scss */
*,
*::before,
*::after {
  box-sizing: inherit; }

/* line 21, src/index.scss */
html {
  box-sizing: border-box; }
  @media only screen and (min-width: 65rem) {
    /* line 21, src/index.scss */
    html {
      font-size: 90%; } }
  @media only screen and (max-width: 65rem) {
    /* line 21, src/index.scss */
    html {
      font-size: 70%; } }
  @media only screen and (max-width: 56.25em) {
    /* line 21, src/index.scss */
    html {
      font-size: 62.5%; } }
  @media only screen and (max-width: 34rem) {
    /* line 21, src/index.scss */
    html {
      font-size: 60%; } }
  @media only screen and (max-width: 20rem) {
    /* line 21, src/index.scss */
    html {
      font-size: 50%; } }

/* line 48, src/index.scss */
body {
  font-family: 'Roboto', 'Oxygen', 'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans', 'Helvetica Neue', sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  font-weight: 400;
  line-height: 1.6;
  min-height: 100vh; }
