/* line 1, src/Main/components/Navigation/Navigation.module.scss */
.navigation {
  background-color: var(--bg-grey-medium);
  display: flex;
  justify-content: space-between;
  color: white; }
  /* line 7, src/Main/components/Navigation/Navigation.module.scss */
  .navigation > * {
    display: flex;
    align-items: center;
    justify-content: center;
    cursor: pointer;
    flex-basis: 20rem; }
  /* line 18, src/Main/components/Navigation/Navigation.module.scss */
  .navigation__logo {
    font-size: 1.5rem; }
