/* line 1, src/Main/components/Landing/InformationSection/InformationSection.module.scss */
.information_section {
  display: flex;
  flex-direction: column;
  align-items: flex-start;
  padding: 3rem 3rem 3rem 10rem;
  font-size: 1rem;
  color: white;
  background-image: linear-gradient(to bottom, rgba(78, 203, 64, 0.8), rgba(67, 87, 61, 0.8)); }
  @media only screen and (max-width: 600px) {
    /* line 1, src/Main/components/Landing/InformationSection/InformationSection.module.scss */
    .information_section {
      font-size: .5rem;
      padding: 2rem 2rem 2rem 6rem; } }
  @media only screen and (max-width: 400px) {
    /* line 1, src/Main/components/Landing/InformationSection/InformationSection.module.scss */
    .information_section {
      padding: 1rem 1rem 1rem 4rem; } }
  /* line 23, src/Main/components/Landing/InformationSection/InformationSection.module.scss */
  .information_section > *:not(:last-child) {
    margin-bottom: 5rem; }
  /* line 28, src/Main/components/Landing/InformationSection/InformationSection.module.scss */
  .information_section__title {
    font-size: 3rem; }
    @media only screen and (max-width: 400px) {
      /* line 28, src/Main/components/Landing/InformationSection/InformationSection.module.scss */
      .information_section__title {
        font-size: 2rem; } }

/* line 37, src/Main/components/Landing/InformationSection/InformationSection.module.scss */
.card__title {
  font-size: 2.5rem; }
  @media only screen and (max-width: 600px) {
    /* line 37, src/Main/components/Landing/InformationSection/InformationSection.module.scss */
    .card__title {
      font-size: 1.5rem; } }
  @media only screen and (max-width: 400px) {
    /* line 37, src/Main/components/Landing/InformationSection/InformationSection.module.scss */
    .card__title {
      font-size: 1rem; } }

/* line 49, src/Main/components/Landing/InformationSection/InformationSection.module.scss */
.card__message {
  font-size: 2rem;
  width: 80vw;
  max-width: 1000px; }
  @media only screen and (max-width: 600px) {
    /* line 49, src/Main/components/Landing/InformationSection/InformationSection.module.scss */
    .card__message {
      font-size: 1rem; } }
  @media only screen and (max-width: 400px) {
    /* line 49, src/Main/components/Landing/InformationSection/InformationSection.module.scss */
    .card__message {
      font-size: .5rem; } }
