/* line 7, src/Main/components/Landing/HeroSection/HeroSection.module.scss */
.hero__section {
  margin-top: 5rem;
  padding: 10rem 6rem;
  z-index: -1;
  color: white;
  text-align: left;
  font-size: 1.75rem;
  background-size: cover;
  background-position: top;
  position: relative;
  border: 5px orangered solid;
  background-image: linear-gradient(to bottom, rgba(126, 213, 111, 0.8), rgba(40, 180, 133, 0.8)), url(../../../assets/images/hero-sm.jpg); }
