/* line 2, src/Main/components/Landing/MoreInfoSection/MoreInfoSection.module.scss */
.more_info_section__title {
  text-transform: uppercase;
  font-size: 2rem; }
  @media only screen and (max-width: 300px) {
    /* line 2, src/Main/components/Landing/MoreInfoSection/MoreInfoSection.module.scss */
    .more_info_section__title {
      font-size: 1rem; } }

/* line 11, src/Main/components/Landing/MoreInfoSection/MoreInfoSection.module.scss */
.more_info_section__back_ground {
  text-align: center;
  padding: 15rem; }
  @media only screen and (max-width: 300px) {
    /* line 11, src/Main/components/Landing/MoreInfoSection/MoreInfoSection.module.scss */
    .more_info_section__back_ground {
      padding: 1rem; } }
  @media only screen and (max-width: 600px) {
    /* line 11, src/Main/components/Landing/MoreInfoSection/MoreInfoSection.module.scss */
    .more_info_section__back_ground {
      padding: 4rem; } }

/* line 24, src/Main/components/Landing/MoreInfoSection/MoreInfoSection.module.scss */
.more_info_section__img {
  max-height: 1200px;
  padding: 1rem;
  height: 15rem;
  margin-top: 2rem; }
  @media only screen and (max-width: 300px) {
    /* line 24, src/Main/components/Landing/MoreInfoSection/MoreInfoSection.module.scss */
    .more_info_section__img {
      height: 8rem;
      padding: 0; } }
